In [1]:
import gym
from gym import spaces
import numpy as np

class TrafficGenerator(gym.Env):
    
    #doesnt really workj
    def getObs(self):
        # Loop over the packet types
        for i in range(len(self.mean_delay)):

            # Get the current queue for the packet type
            current_queue = self.queues[i]

            # Calculate the length and average waiting time of the current queue
            current_length = len(current_queue)
            current_waiting_time = np.average(current_queue) if current_length > 0 else 0.0
            print(np.average(current_queue), current_length, current_waiting_time )
            
            
           
            observation.append([current_length, current_waiting_time])

       
        observation = np.array(observation)
        return observation
    
    def __init__(self):
        
        self.action_space = spaces.Discrete(3)
        
        # Define the observation space (number of packets in each queue and their waiting time)
        self.observation_space = spaces.Box(low=0, high=np.inf, shape=(3,2), dtype=int)
        
        # pancket info (DataType, arrival_rate, mean_delay )
        #self.packetInfo = [[0, 0.3, 6],[1, 0.25, 4],[2, 0.4, float('inf')]]
        
        self.dataType = [0, 1, 2]
        self.arrival_rate = [0.6, 0.4, 0.4]
        self.mean_delay = [6, 4, float('inf')]
        self.packetInfo = [[elem1, elem2, elem3] for elem1, elem2, elem3 in zip(self.dataType, self.arrival_rate, self.mean_delay)]
        
        self.packet = 1
        self.timeslot = 1
        
        # Initialize the queues
        self.queues = [[], [], []]
      
    
    def step(self, action):  
        #packet generator
        for i in range(len(self.packetInfo)):
            for sublist in self.packetInfo:
                if sublist[0] == i and np.random.uniform() < sublist[1]:
                    self.queues[i].append(self.packet)
                    print("Appending to queue", i)
        
        for i in range(len(self.queues)):
            for j in range(len(self.queues[i])):
                self.queues[i][j] -= self.timeslot
                
        
        # services the queues
        for i in range(len(self.queues)):
            print("queue ", i, ": has a length of", len(self.queues[i]))
        print("ACTION queue ", action, ": has a length of", len(self.queues[action]))
        if action < 3 and len(self.queues[action]) > 0:
            self.queues[action].pop(0)
            for i in range(len(self.queues[action])):
                self.queues[action][i] -= 1
        

        
        #TODO rewardoptions?
        
         # Loop over the packet types
        observation = []
        for i in range(len(self.mean_delay)):

            # Get the current queue for the packet type
            current_queue = self.queues[i]

            # Calculate the length and average waiting time of the current queue
            current_length = len(current_queue)
            current_waiting_time = np.average(current_queue) if current_length > 0 else 0.0
            #print(np.average(current_queue), current_length, current_waiting_time )
            
            
    
            observation.append([current_length, current_waiting_time])

        observation = np.array(observation)
        
        done = len(self.queues[0]) + len(self.queues[1]) + len(self.queues[2]) == 0
        return observation, done
        
    def reset(self):
        # Reset the queues
        self.queues = [[], [], []]
        return np.array([[len(self.queues[i]), 0.0] for i in range(len(self.mean_delay))])
        
    def render(self):
        pass

In [2]:
env = TrafficGenerator()
obs = env.reset()
done = False
x = 0
while x < 100:
    print("~~~~~~~~~")
    print(obs[:, 0])
    
    if obs[:, 0][0] > 0 or obs[:, 0][1] > 0:
        action = np.argmax(obs[:2, 0])
    else:
        action = 2 
    
    print("chosen", action)
    obs, done = env.step(action)
    print(obs)
    x = x +1

~~~~~~~~~
[0. 0. 0.]
chosen 2
Appending to queue 0
Appending to queue 1
queue  0 : has a length of 1
queue  1 : has a length of 1
queue  2 : has a length of 0
ACTION queue  2 : has a length of 0
[[1. 0.]
 [1. 0.]
 [0. 0.]]
~~~~~~~~~
[1. 1. 0.]
chosen 0
Appending to queue 1
queue  0 : has a length of 1
queue  1 : has a length of 2
queue  2 : has a length of 0
ACTION queue  0 : has a length of 1
[[ 0.   0. ]
 [ 2.  -0.5]
 [ 0.   0. ]]
~~~~~~~~~
[0. 2. 0.]
chosen 1
Appending to queue 0
Appending to queue 1
queue  0 : has a length of 1
queue  1 : has a length of 3
queue  2 : has a length of 0
ACTION queue  1 : has a length of 3
[[ 1.   0. ]
 [ 2.  -1.5]
 [ 0.   0. ]]
~~~~~~~~~
[1. 2. 0.]
chosen 1
queue  0 : has a length of 1
queue  1 : has a length of 2
queue  2 : has a length of 0
ACTION queue  1 : has a length of 2
[[ 1. -1.]
 [ 1. -3.]
 [ 0.  0.]]
~~~~~~~~~
[1. 1. 0.]
chosen 0
Appending to queue 0
queue  0 : has a length of 2
queue  1 : has a length of 1
queue  2 : has a length of 0
ACT